import Link from "next/link";
import Image from 'next/image'
import Head from 'next/head'

const Navbar = ()=> {
  return(
    <>
    <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
      {`
        .navbar{
          box-shadow: 0.5px 0.5px 5px 2px black;
       scroll-margin-bottom: 5px;
        }
         `}
      </style>
    <nav className="navbar navbar-expand-lg bg-light navbar-light">
  <div className="container-fluid">
    <a className="navbar-brand" href="/">
      <Image src="/logo.png" alt="Physics.Sci" width="250" height="50" className="d-inline-block align-text-top"></Image>
      </a>
      
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div className="navbar-nav">
        <a className="nav-link active" aria-current="page" href="#">Home</a>
        <Link href="Semister-I"><a className="nav-link">Semister-I</a></Link>
        <Link href="Semister-II"><a className="nav-link">Semister-II</a></Link>
    </div>
    </div>
    </div>
    </nav> 
    </>
  );
};

export default Navbar;